spring.application.name=GebxByBlog
server.port=9090

# Koneksi Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email

# Koneksi MongoDB Lokal (Tanpa Password)
#spring.data.mongodb.uri=mongodb://localhost:27017/gebxby_db
#spring.data.mongodb.uri=mongodb+srv://blog_db:<residentevilblogdemandiri1256>@cluster0.aogm44s.mongodb.net/blog_db?appName=Cluster0
spring.data.mongodb.uri=mongodb+srv://blog_db:<residentevilblogdemandiri1256>@cluster0.aogm44s.mongodb.net/blog_db?retryWrites=true&w=majority