spring.application.name=GebxByBlog
server.port=9090
server.forward-headers-strategy=framework
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true
# Koneksi Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email

# Koneksi MongoDB Lokal (Tanpa Password)
#spring.data.mongodb.uri=mongodb://localhost:27017/gebxby_db
# Koneksi MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://${uName_DB}:${pw_DB}@cluster0.aogm44s.mongodb.net/${uName_DB}?retryWrites=true&w=majority
