spring.application.name=GebxByBlog
server.port=9090

# Koneksi Google OAuth2
spring.security.oauth2.client.registration.google.client-id=807668507630-j8ubpnjh54h5tbtp0gipvp1f3ndjstf9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile, email

# Koneksi MongoDB Lokal (Tanpa Password)
spring.data.mongodb.uri=mongodb://localhost:27017/gebxby_db
#spring.data.mongodb.uri=mongodb+srv://blog_db:<residentevilblogdemandiri1256>@cluster0.aogm44s.mongodb.net/blog_db?appName=Cluster0
#spring.data.mongodb.uri=mongodb+srv://blog_db:<residentevilblogdemandiri1256>@cluster0.aogm44s.mongodb.net/blog_db?retryWrites=true&w=majority